### ISSUE TITLE
Game doesn't boot if using anything other than 0.0.2-hotfix-3

### ISSUE THREAD

**Issue by ptkato** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#232] opened 2020-04-24 19:37 UTC
0.0.2-hotfix-3 was the first revision I used, upgrading to newer versions just make the game to get stuck in the first loading screen. Disabling the mod or using 0.0.2-hotfix-3 makes the game work fine.

Am I missing something? From the configurations in the main menu, the only thing I'm using is the option to skip the intro screen.

**Comment by Tyler-IN** [comment] 2020-04-25 14:00
It's probably related to other mods you're using - try dragging Community Patch down toward the bottom. It should be fixed in the upcoming release.

**Comment by ptkato** [comment] 2020-04-25 17:46
I tried moving Community Patch to the end of the load order and there's no difference, I even tried removing all the other mods and leaving only the Community Patch, it also didn't work.

Except now the game doesn't get stuck in the first loading screen, it straight up closes.

**Closed** 2020-05-05 02:44 UTC
Labels: bug, submitter feedback needed

**Comment by Gallaecio** [comment] 2020-05-05 14:53
Is there some way we can help to debug this issue, or since only 2 people so far seem able to reproduce it, it cannot be fixed?

@ptkato Are you on Windows and using the regular launcher? I’m running the game on Linux, including using the non-.NET launcher which causes a loss of performance but a gain in stability.

**Comment by Gallaecio** [comment] 2020-05-05 14:56
Oh, I’ve just noticed a comment by @ptkato on https://github.com/ValveSoftware/Proton/issues/3706#issuecomment-623143422, so we are probably on the same boat, and I’m guessing supporting Linux is out of the scope of this mod.

I’ll continue to use `0.0.2-hotfix-3` for as long as I can, and hope that by the time they release a game version where the mod no longer works they will have fixed most of the stuff in the game itself.
