### ISSUE TITLE
Prominence perk not working 1.4.1

### ISSUE THREAD

**Issue by eli486888** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#332] opened 2020-05-17 17:24 UTC
Hey first thank you all for doing such an amazing job,
I have problem with last update the perk Prominence seems not to work for me, may I ask you guys if you have this issue?

**Comment by JoeFwd** [comment] 2020-05-17 22:10
Duplicate of https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/issues/318.

**Comment by iPherian** [comment] 2020-05-17 23:00
Duplicate of #318

**Comment by iPherian** [comment] 2020-05-17 23:00
I just really like that github timeline note ;)

**Closed** 2020-06-05 03:36 UTC
Labels: duplicate
