### ISSUE TITLE
TramplerPatch2 Crash on M&B 1.4.1 and CP v0.1.0-rc4

### ISSUE THREAD

**Issue by harlanrs** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#293] opened 2020-05-12 01:30 UTC
A crash appears immediately on contact with enemy while on a horse and only appeared after updating to newest release of CP mod. I verified and could reproduce even after disabling every other mod (except one non-combat mod that breaks saves on removal)

Crash trace:
> ---------------------------
> Mount and Blade Bannerlord has crashed
> ---------------------------
> Mount and Blade Bannerlord has encountered an error and needs to close. See the error information below.
> 
> NullReferenceException:
> 
> Object reference not set to an instance of an object.
> 
> 
> 
> Stack trace:
> 
>    at DMD<DMD<__refget_Object_fi_AttackerAgentCharacter>?29840268::__refget_Object_fi_AttackerAgentCharacter>(Object )
> 
>    at CommunityPatch.Patches.Perks.Endurance.Riding.TramplerPatch2.UpdateCorrectCharacterForHorseChargeDamagePostfix(Object& __instance, Agent attackerAgent, AttackCollisionData& attackCollisionData)
> 
>    at DMD<DMD<.ctor_Patch1>?45319986::.ctor_Patch1>(AttackInformation& this, Agent attackerAgent, Agent victimAgent, GameEntity hitObject, AttackCollisionData& attackCollisionData)
> 
>    at TaleWorlds.MountAndBlade.Mission.GetAttackCollisionResults(Agent attackerAgent, Agent victimAgent, GameEntity hitObject, Single momentumRemaining, AttackCollisionData& attackCollisionData, Boolean crushedThrough, Boolean cancelDamage, WeaponComponentData& shieldOnBack)
> 
>    at TaleWorlds.MountAndBlade.Mission.ChargeDamageCallback(AttackCollisionData& collisionData, Blow b, Agent attacker, Agent victim)
> 
>    at ManagedCallbacks.CoreCallbacksGenerated.Mission_ChargeDamageCallback(Int32 thisPointer, AttackCollisionData& collisionData, Blow b, Int32 attacker, Int32 victim)
> 
>    at TaleWorlds.MountAndBlade.MissionState.TickMission(Single realDt)
> 
>    at TaleWorlds.MountAndBlade.MissionState.OnTick(Single realDt)
> 
>    at TaleWorlds.Core.GameStateManager.OnTick(Single dt)
> 
>    at TaleWorlds.Core.Game.OnTick(Single dt)
> 
>    at TaleWorlds.Core.GameManagerBase.OnTick(Single dt)
> 
>    at DMD<DMD<OnApplicationTick_Patch1>?1954641::OnApplicationTick_Patch1>(Module this, Single dt)
> 
> 
> ---------------------------
> OK   
> ---------------------------

**Comment by Tyler-IN** [comment] 2020-05-12 01:38
It's strange, since the NRE is occurring in the field ref dynamic method, it means the instance is null, but I'm not sure if that's  possible... trying to recreate...

**Comment by PackOfDingoes** [comment] 2020-05-12 01:42
https://puu.sh/FJhmg.png

I have the issue too, I believe the above picture shows it, looks exactly the same

**Comment by PackOfDingoes** [comment] 2020-05-12 01:44
I however wasn't the one to do ramming, [this](https://puu.sh/FJhp0.jpg) is the last picture capture I had. So one of the units must have triggered it

**Comment by iPherian** [comment] 2020-05-12 01:51
@harlanrs @PackOfDingoes i don't suppose either of you have a save that can reproduce this? Preferrably with a minimal amount of mods?

**Comment by genisaurus** [comment] 2020-05-12 02:04
@iPherian [Here's a save](https://mega.nz/file/DA9HDbJZ#9LiWfmKeZdWveshto6SdEudH23ap9RBNNjydvLP0Wog) that reproduces the above bug, with all mods disabled (I can produce a list of mods that were in use when the save file was originally created, if needed).
**Steps to reproduce:**
1. The party contains 4x Aserai Noble Sons, set them to unit 8
2. Engage the pack of 7x Looters next to the PC
3. Select unit 8 and F1, F3. The game will crash as soon as the Aserai Noble Sons contact the looters.

**Comment by PackOfDingoes** [comment] 2020-05-12 02:05
I was just uploading mine, but with australian internet it takes ages, so glad you swooped in lol.

**Comment by harlanrs** [comment] 2020-05-12 02:07
Was just about to upload as well. LMK if y'all want any more saves to test against. 

Thanks for the responses as well. I appreciate the work y'all put in.

**Comment by ziomekpl18** [comment] 2020-05-12 02:11
Also happened to me, new save, just met looters, and crash on contact.

**Comment by iPherian** [comment] 2020-05-12 02:16
@genisaurus thanks for the save and detailed instructions!

**Comment by Tyler-IN** [comment] 2020-05-12 02:19
UpdateCorrectCharacterForHorseChargeDamagePostfix is getting a ref of a struct as an argument.

here's the issue... This is a constructor on a type that doesn't exist on previous versions. Referring to the type directly works, but breaks the build against older versions of the game.

Since the fallback "ref object" is supposed to work for __instance according to documentation, that's what it was changed to. Harmony doesn't box the struct ref and sets __instance to null, so that sucks.

So we need to use 'void *' instead and then make a ref pointer/setter. I'm working on it.

**Comment by Tyler-IN** [comment] 2020-05-12 03:49
Needs confirmation that it's fixed in rc5.

**Comment by Mattar19K** [comment] 2020-05-12 03:54
RC5 fixed the issue for me.

**Comment by harlanrs** [comment] 2020-05-12 03:55
Fixed for me as well!

**Comment by Solganis** [comment] 2020-05-12 03:55
No crash so far for me in 2 battles with a lot of Cav units.

**Comment by Tyler-IN** [comment] 2020-05-12 03:59
Ok, closing under the assumption it's fixed. Feel free to ping this issue or post a dupe if something happens that seems related.

**Comment by Tyler-IN** [comment] 2020-05-12 07:17
Not quite fixed. Might still crash when getting trampled and some other variations.

Needs more testing.

**Comment by Tyler-IN** [comment] 2020-05-12 22:04
This is still bugged in custom battle. Need to work out what to do about lack of perks.

**Comment by JoeFwd** [comment] 2020-06-16 15:11
This has been fixed with the latest releases. Closing

**Closed by JoeFwd** 2020-06-16 15:11 UTC
Labels: bug
