### ISSUE TITLE
Issue loading save, v0.0.2

### ISSUE THREAD

**Issue by Chiiklez** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#84] opened 2020-04-09 07:41 UTC
Just updated the patch, tried to load save and got this crash report.

https://gyazo.com/cc92e18540636b4b1ee43e4fe697a8b6

**Comment by tynakuh** [comment] 2020-04-09 07:48
Could you send a save file, privately via discord works too?

**Comment by Chiiklez** [comment] 2020-04-09 08:18
Seems to be an issue with one of my other mods. I have a bunch so not surprising. I started a new campaign with just the patch and it is working fine.

**Comment by tynakuh** [comment] 2020-04-09 08:29
Based on that stacktrace I don't think so, i'll add a mitigation to an upcoming hotfix

**Comment by tynakuh** [comment] 2020-04-09 09:32
Duplicate of #85 please move conversations to that ticket.

**Closed by tynakuh** 2020-04-09 09:32 UTC
