### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Pluviophille** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#237] opened 2020-04-25 21:02 UTC
Game version: 1.2.0
Mod version: v0.0.2-hotfix-5

A whole bunch of other mods are installed along with essentials such as fixed launcher, modlib etc...

Game crashes with the error message below on start.
![Annotation 2020-04-25 135300](https://user-images.githubusercontent.com/64332208/80290856-4888e380-86fd-11ea-813d-d022745a8fd3.jpg)

**Comment by iPherian** [comment] 2020-04-25 21:19
I believe this is fixed in upcoming release 0.1.0. You can try installing the beta for that [here](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/releases/tag/0.1.0-rc2). Vortex manual install will work (CommunityPatch.zip).

Alternatively you can wait for the full release.

**Comment by iPherian** [comment] 2020-04-25 21:19
Duplicate of #169

**Closed** 2020-05-12 22:20 UTC
Labels: duplicate
