### ISSUE TITLE
War Rations: just picked the perk up but my army's food consumption didn't change

### ISSUE THREAD

**Issue by VBMeireles** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#313] opened 2020-05-14 14:29 UTC
Has War Rations been "implemented" by Community Patch at all, though? Since I'm not sure but saw it doesn't work, decided to open an issue for it anyway.

**Comment by JoeFwd** [comment] 2020-06-16 15:10
War rations works as intended. Closing

**Closed by JoeFwd** 2020-06-16 15:10 UTC
Labels: bug
