### ISSUE TITLE
Crash on main map

### ISSUE THREAD

**Issue by ExoLyzix** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#86] opened 2020-04-09 09:26 UTC
I was traveling to a city when this crash occured

![crash](https://user-images.githubusercontent.com/63397512/78879929-e4a3c100-7a54-11ea-868b-d60d78a052b1.png)

**Comment by tynakuh** [comment] 2020-04-09 09:27
Hey, just released a hotfix for this, could you download that and see if that solves your issue?

**Comment by tynakuh** [comment] 2020-04-09 09:32
Duplicate of #85 please move conversations to that ticket.

**Closed by tynakuh** 2020-04-09 09:32 UTC
